[default]

[default.db]
uri = ""
connect_args = {check_same_thread=false}
echo = false

[default.security]
# Secret key is set on .secrets.toml or via envvar SCORE_SECRET_KEY=...
# SECRETE_KEY=""
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRES_MINUTES = 600

